# Generated by Django 2.0.5 on 2018-05-05 18:30

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, help_text='Загрузите изображение', upload_to=gallery.models.directory_path, verbose_name='Скриншоты проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('slug_header', models.SlugField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Адрес сайта')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('category', models.CharField(blank=True, choices=[('sites', 'Сайты'), ('games', 'Игры'), ('software', 'Софт')], default='sites', max_length=30, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, verbose_name='Видео')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Project')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Project'),
        ),
    ]
