# Generated by Django 2.0.5 on 2018-05-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creation_date_time',
            new_name='created',
        ),
    ]
