# Generated by Django 2.0.5 on 2018-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180505_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='slug_header',
            new_name='slug_title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='header',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок'),
        ),
    ]
