# Generated by Django 2.0.5 on 2018-05-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180509_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='gallery.Project'),
        ),
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.Project'),
        ),
    ]
